apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 825383811744.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 825383811744.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: 99b9b6ce
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
